services:
  auth:
    restart: always
    build: ./auth
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: my-secret-pw
      DB_NAME: authdb
    networks:
      - app-net
  ui:
    restart: always
    build: ./UI
    depends_on:
      - auth
      - weather
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
    ports:
      - "3000:3000"
    networks:
      - app-net
  weather:
    restart: always
    build: ./weather
    environment:
      APIKEY: 6d92c50bdamsh81137f3b87ace1fp1d53eejsnfe818b9dbc83
    networks:
      - app-net
  db:
    restart: always
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: authdb
    networks:
      - app-net
    volumes:
      - ./db-data:/var/lib/mysql

networks:
  app-net:
    driver: bridge
volumes:
  db-data: